main-page:
  unlogin: newcomer
  "2023": newcomer
  default: at-school

main-presets:
  newcomer:
    - tag: card
      cover: http://mmbiz.qpic.cn/mmbiz_jpg/1LGPufKFDrdWYjcsI2ku82lich9RJa567Mcx9PicslCC4FRwMNpLCKHzliaAX4NQEJP4elHysSZibWqxGiaK71iaL0Gw/0?wx_fmt=jpeg&amp;random=0.23670275764878745
      title: 2023级辅导员大揭秘
      path: /newcomer/intro/counselor/2023

    - tag: grid
      header: 您可能想关注
      items:
        - text: 账号激活
          color: grey
          name: Activate
          icon: authorize
          url: activate

        - text: 新生入学教育
          color: blue
          name: Edu Course
          icon: study
          path: newcomer/yiban/

        - text: 企业号认证
          color: blue
          name: Wechat
          icon: wechat
          path: guide/account/wechat/

        - text: 新生群
          color: olive
          name: Contact
          icon: qq-group
          path: newcomer/contact/

        - text: 新生攻略视频
          color: red
          name: Video
          icon: media
          path: newcomer/video

        - text: 寝室
          color: blue
          name: Dorm
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          color: orange
          name: Dining
          icon: dining
          path: guide/dining/

        - text: 洗浴
          color: red
          name: Bath
          icon: bath
          path: guide/bath/

        - text: 生活
          color: purple
          name: Life
          icon: life
          path: guide/life/

        - text: 专业介绍
          color: olive
          name: Major
          icon: about
          path: school/major

        - text: 转专业
          color: red
          name: Change Major
          icon: change
          path: guide/change-major/

        - text: 师范生
          color: purple
          name: Normal
          icon: teacher
          path: guide/normal/

        - text: 课程
          color: orange
          name: Course
          icon: content
          path: guide/course/

        - text: 学习
          color: mauve
          name: Study
          icon: study
          path: guide/study/

        - text: 校历
          color: mauve
          name: Calendar
          icon: calendar
          url: calendar

        # - text: 常见问题
        #   color: cyan
        #   name: FAQ
        #   icon: faq
        #   path: newcomer/faq/

      footer: 更多内容请详见下方其他 Tab 页

    - tag: card
      cover: https://assets.innenu.com/img/tab/faq.png
      title: 常见问题
      logo: faq
      url: info?path=/newcomer/faq/

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 成绩查询
          color: orange
          name: Grade
          icon: grade
          url: course-grade

        - text: 选课系统
          color: blue
          name: Select
          icon: select
          url: select

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

        - text: 校历
          color: mauve
          name: Calendar
          icon: calendar
          url: calendar

      footer: 更多内容请详见下方其他 Tab 页

intro-page:
  unlogin:
    items:
      - under-enroll
      - grad-enroll
      - about
      - school
    more:
      - apartment
  "2023":
    items:
      - about
      - school
    more:
      - under-enroll
      - grad-enroll
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  unlogin:
    items:
      - newcomer
      - life
      - study
      - account
    more:
      - service
      - tip
      - enjoy
      - graduate
  "2023":
    items:
      - newcomer
      - life
      - study
      - service
      - account
      - tip
      - enjoy
    more:
      - graduate
  "2020":
    items:
      - graduate
      - study
      - service
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer
  default:
    items:
      - service
      - study
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  unlogin: unlogin
  "2023": newcomer
  default: at-school

function-presets:
  newcomer:
    # - tag: card
    #   cover: https://assets.innenu.com/img/tab/calendar.jpg
    #   title: 校历
    #   logo: calendar
    #   url: calendar

    # - tag: card
    #   cover: https://assets.innenu.com/img/tab/map.jpg
    #   title: 校园地图
    #   logo: map
    #   url: map

    # - tag: card
    #   cover: https://assets.innenu.com/img/tab/admission.jpg
    #   title: 录取查询
    #   logo: letter
    #   url: admission?type=search

    # - tag: card
    #   cover: https://assets.innenu.com/img/tab/headphone.jpg
    #   title: 音悦东师
    #   logo: cd
    #   url: music

    # - tag: card
    #   cover: https://assets.innenu.com/img/tab/video.jpg
    #   title: 影约东师
    #   logo: media
    #   url: video?type=video

    - tag: grid
      header: 本科招生
      items:
        - text: 2023 年招生简章
          name: Rule
          color: blue
          icon: rule
          path: intro/enroll/under/rule/

        #     - text: 2023 年招生计划
        #       name: Plan
        #       color: orange
        #       icon: enroll
        #       url: enroll-plan

        #     - text: 历史分数
        #       name: History grade
        #       color: purple
        #       icon: time
        #       url: enroll-grade

        - text: 录取查询
          name: Admission
          color: cyan
          icon: letter
          url: admission?type=search

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 音悦东师
          color: blue
          name: Music
          icon: cd
          url: music

        - text: 影约东师
          color: mauve
          name: Media
          icon: media
          url: video?type=video

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

        - text: 校园邮箱
          color: purple
          name: Email
          icon: email
          url: email

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: info-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: info-list?type=news

        - text: 学术会议
          color: cyan
          name: News
          icon: study
          url: info-list?type=academic

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 功能
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 成绩查询
          color: orange
          name: Grade
          icon: grade
          url: course-grade

        - text: 内网通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 内网新闻
          color: cyan
          name: News
          icon: news
          url: notice-list?type=news

        - text: 选课系统
          color: blue
          name: Select
          icon: select
          url: select

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

      footer: " "

  at-school:
    - tag: grid
      header: 功能
      items:
        - text: 课程表
          color: grey
          name: Course
          icon: course-table
          url: course-table

        - text: 成绩查询
          color: orange
          name: Grade
          icon: grade
          url: course-grade

        - text: 内网通知
          color: red
          name: Notice
          icon: notice
          url: notice-list

        - text: 内网新闻
          color: cyan
          name: News
          icon: news
          url: notice-list?type=news

        - text: 校园邮箱
          color: purple
          name: Email
          icon: email
          url: email

        - text: 选课系统
          color: blue
          name: Select
          icon: select
          url: select

        - text: 图书馆
          color: purple
          name: Library
          icon: library
          url: library

        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: info-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: info-list?type=news

        - text: 学术会议
          color: cyan
          name: News
          icon: study
          url: info-list?type=academic

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 招生相关
      items:
        - text: 2023 年招生简章
          name: Rule
          color: blue
          icon: rule
          path: intro/enroll/under/rule/

        # - text: 2023 年招生计划
        #   name: Plan
        #   color: orange
        #   icon: enroll
        #   url: enroll-plan

        # - text: 历史分数
        #   name: History grade
        #   color: purple
        #   icon: time
        #   url: enroll-grade

        - text: 录取查询
          name: Admission
          color: cyan
          icon: letter
          url: admission?type=search

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 音悦东师
          color: blue
          name: Music
          icon: cd
          url: music

        - text: 影约东师
          color: mauve
          name: Media
          icon: media
          url: video?type=video

      footer: " "

  unlogin:
    - tag: grid
      header: 账号激活
      items:
        - text: 账号激活
          color: grey
          name: Activate
          icon: authorize
          url: activate

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          color: orange
          name: Map
          icon: map
          url: map

        - text: 音悦东师
          color: blue
          name: Music
          icon: cd
          url: music

        - text: 影约东师
          color: mauve
          name: Media
          icon: media
          url: video?type=video

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          color: olive
          name: Calendar
          icon: calendar
          url: calendar

        - text: 校园媒体
          color: grey
          name: Accounts
          icon: account
          url: school-media

        - text: 学校通知
          color: red
          name: Notice
          icon: notice
          url: info-list

        - text: 学校新闻
          color: cyan
          name: News
          icon: news
          url: info-list?type=news

        - text: 学术会议
          color: cyan
          name: News
          icon: study
          url: info-list?type=academic

        - text: 东师网站
          color: orange
          name: Websites
          icon: network
          url: website

        - text: 师大黄页
          color: purple
          name: Contact
          icon: phone
          url: phone

    - tag: grid
      header: 功能
      items:
        - text: 体测计算器
          color: olive
          name: PE Calculator
          icon: calculate
          url: pe-calculator

    - tag: list
      items:
        - text: 登录开启更多功能
          url: account
      footer: " "

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: functional-list
    items:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 评价小程序
        icon: star
        type: button
        handler: rate

      - text: 联系校会君
        icon: contact
        type: button
        openType: contact

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序由校团委融媒体中心授权交由 Mr.Hope 开发。其全部代码均由 Mr.Hope 编写，其内容仅代表 Mr.Hope 个人观点。

      - text: 小程序现有字数为 981875 字，其中东师指南部分 363320 字，新生迎新部分 101374 字，东师介绍部分 217194 字，机构介绍部分 67029 字，学院介绍部分 143935 字，功能大厅部分 41566 字，其他部分 47457 字。

      - text: 校团委融媒体中心介绍
        url: info?path=Gorg/new-media-center

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: text
    heading: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  course-grade: local
  course-table: local
  info-detail: local
  info-list: local
  enroll-grade: local
  enroll-plan: local
  notice-detail: local
  notice-list: local
  email: local

notice:
  app:
    title: 欢迎使用『东师青年+』
    content: 欢迎使用东师青年+。这是一个由校团委融媒体中心授权 Mr.Hope 个人开发制作的小程序，内含 98 万字的新生攻略。小程序内容仅代表 Mr.Hope 的个人观点，希望大家能够通过小程序摆脱对大学的迷茫。
  activate:
    title: 手机验证码
    content: 学校的短信验证服务发送验证码有较高延迟，请耐心等待。另外部分手机号可能收不到验证码，遇到此情况可更换家人号码尝试激活。

update:
  force: false
  reset: false
