title: in 东师 QQ 小程序隐私说明
author: Mr.Hope
time: 2023-06-21T05:51:19.919Z
shareable: true
content:
  - tag: title
    text: in 东师 QQ 小程序隐私说明

  - tag: text
    text: 本说明是 in 东师小程序开发者 Mr.Hope (以下简称“开发者”) 对在小程序中获取、处理你的相关隐私信息而指定。

  - tag: text
    heading: 1. 开发者处理的信息
    text:
      - 根据法律规定，开发者仅处理实现小程序功能所必要的信息。

  - tag: ul
    text:
      - 为了保存小程序二维码到你的相册，开发者将在获取你的明示同意后，使用你的相册(仅写入)权限。你在分享菜单中点击“保存二维码”按钮后，小程序会使用此权限保存小程序二维码到你的相册。
      - 开发者使用你的通讯录(仅写入)权限，用于保存学校相关电话到你的通讯录。在你电话列表中点击“添加联系人”按钮后，小程序会保存相关联系人信息到你的通讯录。
      - 为了校园导航，开发者将在获取你的明示同意后，获取你的位置信息并显示在地图上。你的位置信息将仅用于小程序内显示，开发者并不会收集并上传任何位置信息。
      - 为了让你快速打开网址与下载链接，开发者将在获取你的明示同意后，写入你的剪切板。你在小程序内点击“复制”按钮后，小程序会将网址或下载链接复制到你的剪贴板。
      - 为了快捷添加好友，开发者将在获取你的明示同意后，使用你的添加好友权限。你在反馈页面勾选“允许开发者联系”后，开发者可能会根据你的反馈内容进一步联系你。
      - 使用东北师范大学校园相关服务时，开发者将要求你输入东北师范大学统一身份认证的账密。该账密仅会存储在本机，并在必要时通过登录接口提交。开发者并不会上传、保存你的学号和密码。
      - 当使用东北师范大学账号激活服务时，开发者将要求你输入你的姓名、考生号、身份证号、学号、手机号、设置密码，这些信息是激活东北师范大学账号激活的必要信息，会直接提供给东北师范大学激活服务。开发者在此过程中并不会上传、保存任何信息。
      - 当使用录取查询服务时，开发者将要求你输入你的姓名、考生号和身份证号，这些信息是东北师范大学录取查询的必要信息，会直接提供给东北师范大学录取查询服务。开发者在此过程中并不会上传、保存任何信息。

  - tag: text
    heading: 2. 第三方插件信息
    text:
      - 为实现特定功能，开发者可能会接入由第三方提供的插件。第三方插件的个人信息处理规则，请以其公示的官方说明为准。

  - tag: list
    header: 接入的第三方插件信息
    items:
      - text: 暂无

  - tag: text
    heading: 3. 你的权益
    text:
      - |-
        3.1 关于“位置信息”，你可以通过以下路径: 小程序主页右上角“…”—“设置”—点击“位置信息”—点击“不允许”，撤回对开发者的授权。
      - |-
        3.2 关于“添加到相册”，你可以通过以下路径: 小程序主页右上角“…”—“设置”—关闭“添加到相册”开关，撤回对开发者的授权。
      - 3.3 关于你的个人信息，你可以通过 mrhope@innenu.com 与开发者联系，行使查阅、复制、更正、删除等法定权利。

  - tag: text
    heading: 4. 开发者对信息的存储
    text:
      - 开发者承诺，除法律法规另有规定外，开发者对你的信息的保存期限应当为实现处理目的所必要的最短时间。

  - tag: text
    heading: 5. 信息的使用规则
    text:
      - 5.1 开发者将会在本说明所明示的用途内使用收集的信息。
      - 5.2 如开发者使用你的信息超出本指引目的或合理范围，开发者必须在变更使用目的或范围前，再次以小程序内通知的方式告知并征得你的明示同意。

  - tag: text
    heading: 6. 信息对外提供
    text:
      - 6.1 开发者承诺，不会主动共享或转让你的信息至任何第三方，如存在确需共享或转让时，开发者应当直接征得或确认第三方征得你的单独同意。
      - 6.2 开发者承诺，不会对外公开披露你的信息，如必须公开披露时，开发者应当向你告知公开披露的目的、披露信息的类型及可能涉及的信息，并征得你的单独同意。

  - tag: text
    heading: 7. 联系开发者
    text: 你认为开发者未遵守上述约定，或有其他的投诉建议、或未成年人个人信息保护相关问题，可通过 mrhope@innenu.com 与开发者联系。
