title: 首页
id: main
grey: true
hidden: true
content:
  - tag: grid
    header: 功能
    items:
      - text: 课程表
        color: grey
        name: Course
        icon: degree
        url: course-table

      - text: 成绩查询
        color: orange
        name: Grade
        icon: grade
        url: course-grade

      - text: 选课系统
        color: blue
        name: Select
        icon: select
        url: select

      - text: 图书馆
        color: purple
        name: Library
        icon: library
        url: library

      - text: 体测计算器
        color: olive
        name: PE Calculator
        icon: calculate
        url: pe-calculator

      - text: 校历
        color: mauve
        name: Calendar
        icon: calendar
        url: calendar

    footer: 更多内容请详见下方其他 Tab 页

  # - tag: card
  #   cover: $img/tab/faq.png
  #   title: 常见问题
  #   logo: faq
  #   url: info?id=/newcomer/faq/

  # - tag: card
  #   cover: https://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
  #   title: 招纳小程序志愿者
  #   logo: $img/inNENU.png
  #   name: in 东师
  #   url: info?path=Oguide/volunteer
