before: []
after: []
data:
  about:
    name: 学校介绍
    path: /intro/about
    items:
      - text: 学校概况
        color: red
        name: Description
        icon: about
        path: about/

      - text: 学科建设
        color: olive
        name: Subject
        icon: content
        path: subject/

      - text: 学生就业
        color: cyan
        name: Job
        icon: job
        path: job/

      - text: 资助
        color: purple
        name: Subsidize
        icon: subsidize
        path: subsidize/

  apt:
    name: 学校机构
    path: /intro/apt/
    items:
      - text: 招生办公室
        color: orange
        name: Enroll
        icon: enroll
        path: apt/enroll/

      - text: 研究生院
        color: grey
        name: Graduate
        icon: degree
        path: apt/grad/

      - text: 信息化办公室
        color: purple
        name: Information
        icon: pc
        path: apt/xxhb/

      - text: 校医院
        color: olive
        name: Hospital
        icon: hospital
        path: apt/hospital/

      - text: 保卫科
        color: mauve
        name: Defend
        icon: police
        path: apt/defend

      - text: 图书馆
        color: cyan
        name: Library
        icon: library
        path: apt/library/

      - text: 学校办公室
        color: red
        name: Office
        icon: office
        path: apt/office/

      - text: 党委学生工作部
        color: blue
        name: Student
        icon: student
        path: apt/student/

      - text: 后勤管理处
        color: cyan
        name: Logistics
        icon: repair
        path: apt/logistics/

      - text: 教务处
        color: blue
        name: Course
        icon: jwc
        path: apt/course/

      - text: 学生就业指导服务中心
        color: cyan
        name: Career
        icon: job
        path: apt/career

      - text: 校团委
        color: purple
        name: League
        icon: $img/about/group.png
        path: apt/youth-league/

      - text: 学生心理健康教育中心
        color: orange
        name: Psychology
        icon: psychology
        path: apt/psychology/

      - text: 档案馆
        color: purple
        name: Archive
        icon: archive
        path: apt/archive/

      - text: 党委宣传部
        color: olive
        name: Publicize
        icon: league
        path: apt/publicize/

      - text: 体育馆
        color: olive
        name: Gym
        icon: basketball
        path: apt/gym/

  school:
    text: 学院介绍
    path: /intro/school/
    items:
      - text: 教育学部
        color: blue
        name: Education
        icon: education
        path: education/

      - text: 心理学院
        color: orange
        name: Psychology
        icon: psychology
        path: psychology/

      - text: 政法学院
        color: red
        name: Politics
        icon: politics
        path: politics/

      - text: 经济与管理学院
        color: purple
        name: Economy
        icon: economy
        path: economy/

      - text: 文学院
        color: cyan
        name: Chinese
        icon: chinese
        path: chinese/

      - text: 历史文化学院
        color: olive
        name: History
        icon: history
        path: history/

      - text: 外国语学院
        color: mauve
        name: Foreign
        icon: foreign
        path: foreign/

      - text: 音乐学院
        color: blue
        name: Music
        icon: music
        path: music/

      - text: 美术学院
        color: orange
        name: Art
        icon: art
        path: art/

      - text: 马克思主义学部
        color: red
        name: Marx
        icon: marx
        path: marx/

      - text: 数学与统计学院
        color: purple
        name: Math
        icon: math
        path: math/

      - text: 信息科学与技术学院
        color: cyan
        name: Politic
        icon: ist
        path: ist/

      - text: 物理学院
        color: olive
        name: Physics
        icon: physics
        path: physics/

      - text: 化学学院
        color: mauve
        name: Chemistry
        icon: chemistry
        path: chemistry/

      - text: 生命科学学院
        color: blue
        name: Biology
        icon: biology
        path: biology/

      - text: 地理科学学院
        color: orange
        name: Geography
        icon: geography
        path: geography/

      - text: 环境学院
        color: red
        name: Env
        icon: environment
        path: environment/

      - text: 体育学院
        color: purple
        name: PE
        icon: basketball
        path: pe/

      - text: 传媒科学学院
        color: cyan
        name: Media
        icon: media
        path: media/

      - text: 国际汉学院
        color: mauve
        name: Internation
        icon: network
        path: internation/

  grad-enroll:
    name: 研究生招生
    path: intro/enroll/grad/
    items:
      - text: 招生简章
        icon: intro
        path: rule/2023

      - text: 招生计划
        icon: intro
        path: major/2023

      - text: 东师研招
        icon: wechat
        url: wechat-detail?path=graduate

      - text: 录取查询
        name: Admission
        color: cyan
        icon: letter
        url: admission?type=search

  under-enroll:
    name: 本科招生
    path: intro/enroll/under/
    items:
      - text: 招生简章
        name: Rule
        color: blue
        icon: rule
        path: intro/enroll/under/rule/

      - text: 招生计划
        name: Plan
        color: orange
        icon: enroll
        url: enroll-plan

      - text: 历史分数
        name: History grade
        color: purple
        icon: time
        url: enroll-grade

      - text: 录取查询
        name: Admission
        color: cyan
        icon: letter
        url: admission?type=search
