# 上次更新于 9/7 0:35
all: 1800
donations:
  - - MING
    - 1.42
  - - v
    - 2
  - - 多多动脑
    - 2
  - - 快乐打工人
    - 4
  - - 海鲜面
    - 2
  - - 有石名黛
    - 4
  - - 庚
    - 6
  - - 好名
    - 2
  - - lisa
    - 8
  - - 一头糖醋蒜
    - 2
  - - 赜琦
    - 2
  - - zzzzlz
    - 4
  - - 永远Karl
    - 2
  - - 最喜欢倩倩姐姐啦~
    - 2
  - - D6
    - 2
  - - [未知用户名]
    - 8
  - - 栖
    - 2
  - - CLARA
    - 2
  - - 小町
    - 2
  - - 阴暗军训预备役之火辣B格
    - 24
  - - 行者有疆
    - 4
  - - 王执中
    - 2
  - - 🐏🐏🐏
    - 4
  - - 绫光phlyer
    - 2
  - - 欧比旺克诺比
    - 6
  - - 璎珞朵朵
    - 18
  - - 小碧心
    - 2
  - - Giselle
    - 2
  - - 来年
    - 2
  - - 杨硕
    - 8
  - - 苍绿
    - 6
  - - 莉
    - 8
  - - ='人'=
    - 8
  - - 肚肚(；\O/)o
    - 4
  - - 日不落行秋
    - 2
  - - 肖春梅
    - 2
  - - 🍭🍀不倒翁🍀🍭
    - 2
  - - D6
    - 6
  - - 波
    - 2
  - - Creep
    - 1
  - - 虿
    - 2
  - - 认识你自己
    - 12
  - - 涵
    - 2
  - - (日文实在打不出来.....)
    - 2
  - - Juliet
    - 1
  - - 拾酒
    - 2
  - - cka
    - 2
  - - 小孩
    - 2
  - - Mononoke
    - 2
  - - 马非马
    - 2
  - - Wave
    - 2
  - - "·_·"
    - 2
  - - 橘子菌
    - 2
  - - Bluederoi
    - 2
  - - 元卞
    - 1
  - - Guinue
    - 2
  - - 小金睡不醒Zzz
    - 8
  - - Mr.Lee
    - 1
  - - Stone
    - 2
  - - morning breeze (能打版
    - 2
  - - 过禾
    - 2
  - - joe
    - 2
  - - 辣椒
    - 2
  - - 写完作业就回家
    - 6
  - - Luna
    - 2
  - - May
    - 2
  - - 伊比利亚小蛋糕🎂
    - 2
  - - 过禾
    - 2
  - - 於万斯年
    - 2
  - - 🎇
    - 1
  - - 🌈
    - 8
  - - 丶东方小妖
    - 2
  - - Spark (大肆哒嘟版)
    - 2
  - - 蕉蕉太狼
    - 2
  - - Milky
    - 2
  - - 予
    - 2
  - - 飞鱼
    - 6
  - - 西坡居士
    - 1
  - - 茫芊
    - 8
  - - 知意
    - 1
  - - (Π_Π)
    - 2
  - - 望仔小添才
    - 2
  - - 绵绵
    - 2
  - - 六便士
    - 6
  - - 潼潼
    - 2
  - - 该网名已被删除
    - 2
  - - Asterion
    - 2
  - - Lea
    - 8
  - - Vsilenstvi
    - 2
  - - 波波
    - 2
  - - Mayfly
    - 1.88
  - - 虎浪嘿🐅
    - 6
  - - 古木朽株
    - 6
  - - lyj
    - 2
  - - now or never
    - 2
  - - 叶瑄老婆
    - 2
  - - |-
      @￥]*t)
    - 6
  - - .22
    - 4
  - - L.
    - 2
  - - 软糖硬吃
    - 2
  - - Re_
    - 2
  - - 念安.
    - 2
  - - 山风
    - 18
  - - 昰言
    - 2
  - - Smile:)
    - 2
  - - A筱
    - 2
  - - 应如是
    - 2
  - - AB
    - 2
  - - Aysm
    - 2
  - - 小t小t
    - 8
  - - ski.di
    - 2
  - - 床
    - 6
  - - 霁月
    - 8
  - - 柒
    - 2
  - - Mq
    - 1
  - - _
    - 6
  - - 迪胖胖呀
    - 8
  - - 帆
    - 2
  - - 云深不知处
    - 2
  - - 曙
    - 2
  - - ✌
    - 2
  - - Flipped
    - 2
  - - 飞鸿踏雪泥
    - 18
  - - Bel-ami
    - 2
  - - "12345"
    - 2
  - - x
    - 8
  - - 🌖
    - 2
  - - Why
    - 8
  - - "@张恒瑞"
    - 2
  - - Kujo Jotaro
    - 2
  - - ENE
    - 6
  - - 十月流光
    - 2
  - - 等到放晴那天了🍂
    - 1
  - - 下眉头上心头
    - 8
  - - 遇语
    - 6
  - - SUNSHINE
    - 2
  - - AAA碧尔盖子在此
    - 6
  - - 白马即墨
    - 2
  - - attached
    - 2
  - - 北方有佳人
    - 8
  - - 在在
    - 2
  - - 乌拉哆啦
    - 6
  - - 寂川
    - 18
  - - QQmian
    - 2
  - - Herision哈里
    - 8
  - - 瘦咸鱼
    - 8
  - - 歌起楚江
    - 6
  - - 孤独星球
    - 2
  - - 我的id呢?
    - 2
  - - 何佳莽
    - 2
  - - 起向未来
    - 1
  - - 正义该溜子大战科二
    - 2
  - - -7³
    - 2
  - - 今盐
    - 2
  - - 豆芽
    - 2
  - - 神落十歌
    - 2
  - - 沙琪玛
    - 2
  - - 言说鳗饺
    - 6
  - - 中华小当当
    - 1
  - - 硬糖
    - 6
  - - Xavier
    - 2
  - - Devoted FUTURE
    - 2
  - - |-
      onandon4: 14
    - 8
  - - LKFWD
    - 2
  - - 肆门
    - 2
  - - 清风故里人
    - 2
  - - 魂
    - 6
  - - 陆王炸
    - 2
  - - N.A
    - 2
  - - 秋冬
    - 6
  - - 烂柯人
    - 2
  - - 振金士豆挠子
    - 2
  - - MADAO
    - 2
  - - 曙色
    - 1.66
  - - 无木息
    - 18
  - - 小新青年
    - 2
  - - 杨枝甘露醇
    - 2
  - - 江酒酒
    - 2
  - - Intrepid
    - 2
  - - Rechlieu
    - 6
  - - 睡觉莓
    - 2
  - - 🚀刘小远
    - 2
  - - wolf_8
    - 6
  - - 不上层楼
    - 18
  - - 唐小桐
    - 8
  - - 洛希极限
    - 2
  - - 🤯🤯🤯
    - 2
  - - 大聪明有大智慧
    - 8
  - - 落月屋梁
    - 1
  - - 叮咚CN
    - 2
  - - 来年
    - 2
  - - 碱性劣等生
    - 1
  - - Quarter
    - 2
  - - Alatreon
    - 6.66
  - - 纪清弦
    - 2
  - - 王落灰
    - 2
  - - 欧比旺克诺比
    - 1.14
  - - ferry
    - 1
  - - 南宫十七
    - 2
  - - Octavia🌠(拾荒版)
    - 2
  - - 要好好睡觉
    - 2
  - - 百事可乐Ovo
    - 2
  - - SALTWATER
    - 2
  - - Felix Felicis
    - 18
  - - 海绵宝宝(放假版)
    - 6
  - - Trigger
    - 2
  - - 海绵宝宝(放假版)
    - 6
  - - 鑫😊
    - 8
  - - (一些我实在打不出来的符号)
    - 8
  - - zzzzlz
    - 2
  - - ASIK
    - 2
  - - 波
    - 8
    - 8
  - - 孙py
    - 6
  - - 董畅达
    - 2
  - - LDN
    - 2
  - - zxp
    - 2
  - - 稼轩
    - 2.1
  - - dallas
    - 18
  - - " "
    - 2
  - - 超级无敌大大垃圾人
    - 2
  - - 太易宇
    - 2
  - - Lumos
    - 2
  - - Hannah's Lemonade
    - 18
