wx9ce37d9662499df3: {}

wx33acb831ee1831a5:
  intro/about/index: "#小程序://in东师/in东师/16Iaw5GxYn5d7ks"
  intro/about/intro: "#小程序://in东师/in东师/Nrl9Fz3vuo2taEo"
  intro/about/locate: "#小程序://in东师/in东师/3gjyRWVjMeQlgQi"
  intro/about/sign: "#小程序://in东师/in东师/j9gzevXpEFvHrgA"
  intro/about/history: "#小程序://in东师/in东师/fn7RjOIChtzwkpJ"
  intro/about/rank: "#小程序://in东师/in东师/3jLUqzmD7hEhedl"
  intro/enroll/index: "#小程序://in东师/in东师/I6sQLekrAqTSgjk"
  intro/enroll/major/2021: "#小程序://in东师/in东师/cu8BCM0A1kG1RuH"
  intro/enroll/rule/2021: "#小程序://in东师/in东师/RUkWv5Wb3FI17Kt"
  intro/enroll/great-normal/2021: "#小程序://in东师/in东师/hNGTH89W3JTsRqn"
  intro/enroll/second-degree/2021: "#小程序://in东师/in东师/8xliraq1Rx60G8c"
  intro/enroll/history: "#小程序://in东师/in东师/CUwW6j58SN1yjoo"
  intro/enroll/major/2020: "#小程序://in东师/in东师/70NclYCxAytVqNs"
  intro/enroll/major/2019: "#小程序://in东师/in东师/pIRPVqx33LNtOSl"
  intro/enroll/search: "#小程序://in东师/in东师/fL8wy5GRInNLz7v"
  intro/enroll/rule/2020: "#小程序://in东师/in东师/D8DNQR3vZirTsFl"
  intro/enroll/rule/2019: "#小程序://in东师/in东师/aVi0mwsicN1LJPq"
  intro/enroll/contact: "#小程序://in东师/in东师/oqXVRNwjfNlY0eH"
  intro/enroll/QQGroup: "#小程序://in东师/in东师/WBBInHUsKzWgP7A"
  intro/enroll/activity: "#小程序://in东师/in东师/K0fKiPn6NjStu2k"
  intro/enroll/intro: "#小程序://in东师/in东师/QDcWOeymeoJ0GoJ"
