title: 功能大厅
id: function
grey: true
hidden: true
content:
  # - tag: card
  #   cover: $img/tab/admission.jpg
  #   title: 录取查询
  #   logo: letter
  #   url: admission

  - tag: card
    cover: $img/tab/map.jpg
    title: 校园地图
    logo: map
    url: map

  - tag: card
    cover: $img/tab/calendar.jpg
    title: 校历
    logo: calendar
    url: calendar

  # - tag: card
  #   cover: $img/tab/headphone.jpg
  #   title: 音悦东师
  #   logo: cd
  #   url: music

  # - tag: card
  #   cover: $img/tab/video.jpg
  #   title: 影约东师
  #   logo: media
  #   url: video?type=video

  - tag: card
    cover: $img/tab/sport-field.jpg
    title: 体测计算器
    logo: calculate
    url: pe-calculator

  # - tag: card
  #   cover: $img/tab/media.jpg
  #   title: 校园媒体
  #   logo: account
  #   url: school-media

  - tag: card
    cover: $img/tab/website.jpg
    title: 东师网站
    logo: network
    url: website

  - tag: card
    cover: $img/tab/phone.jpg
    title: 师大黄页
    logo: phone
    url: phone
